# -*- coding: utf-8 -*-
"""tanveer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJ9acpk42FWmHpZ5BuZWVN3xHx8UrCw_

Print the squares of the elements of list [2,4,5,7,8,9,10,22]
"""

num = [2, 4, 5, 7, 8, 9, 10, 22]

for i in num:
    print(i**2)

"""# 2 . Print Odd numbers between 1 to 100."""

for i in range (1,101):
  if (i%2!=0):
    print(i)

"""# 3. Take X as int input from user, print the 10 element of following series:
X, X3,, X5, X7...
"""

x = int(input('ENTER YOUR INT INPUT  '))
for i in range(x) :
  print(i)

"""# 4. To design your own count function. Find the number of times an element is
present in a list [2,3,4,5,6,2,3,4,2,3,4,2]. Take the element as input from the
user. Don’t use predefined methods, use loop and give the answer.
"""

not understand

"""# 5. Design your own upper function. Take the user name as input from the user
and convert it to upper case without using predefined upper method.
"""

name = input('ENTER YOUR NAME ')


not understand

"""# 7. Take an int number input from user and print the sum of digits of the number."""

num = input("Enter a number: ")

x = 7
for i in num:
    x += int(num)

print("Sum of digits:", x)

"""#  """